@startuml
title DA1: Vue client 360
:Consulter dossier client;

	split
		:Rechercher contrat client;
	split again
		:Detailler dernier contrat client;
	split again
		:Consulter un contact;
	split again
		:Creer contact;
	split again
		:Consulter information personne;
	split again
		:Consulter liste contacts client;
	end split

@enduml
