@startuml
title DA1: Vue client 360\n
:Consulter dossier client;

split
    :Gérer les contrats;
split again
    :Gérer contacts;
split again
    :Gérer les personnes;
end split

@enduml
