@startuml
title DSA003 - Gestion des contacts

actor Agent
participant Interface as IHM
participant "Services\nMétier\nApplicatifs" as SMA
participant Client
participant Contact as C
participant Structure
participant Personne
participant Contrat

== Consulter dossier client ==

'Lister les contacts d'un client
Agent -->> IHM: consulterDossierClient
    IHM -> SMA: consulterDossierClient(**idClient**)
    activate SMA
        SMA -> Client: obtenirDonneesVue360(**idClient**)
        activate Client
        SMA <<-- Client: //Client, Liste<idPersonne>//
        deactivate Client

        SMA -> C: obtenirDerniersContacts(**idClient**)
        activate C
        SMA <<-- C: //Liste<Contact, idAgent>//
        deactivate C

        group Pour chaque //idAgent// de //Liste<Contact, idAgent>//
            SMA -> Structure: obtenirAgentParId(**idAgent**)
            activate Structure
            SMA <<-- Structure: //Agent//
            deactivate Structure
        end

        group Pour chaque //idPersonne// de //Liste<idPersonne>//
           SMA -> Personne: obtenirPersonne(**idPersonne**)
           activate Personne
           SMA <<-- Personne: //Personne, Adresse//
           deactivate Personne
        end

        SMA -> Contrat: obtenirDerniereSouscriptionParIdClient(**idClient**)
        activate Contrat
        SMA <<-- Contrat: //Souscription, Contrat, Domaine//
        deactivate Contrat

        SMA -> Contrat: compterSouscriptionsParDomaine(**idClient**)
        activate Contrat
        SMA <<-- Contrat: //totalSouscriptions, Liste<Domaine, quantité>//
        deactivate Contrat

    IHM <<-- SMA: //Client, Liste<Contact, Agent>, Liste<Personne>//\n//Souscription, Contrat, Domaine, totalSouscriptions,//\n//Liste<Domaine, quantité>//
    deactivate SMA

'Fin: Consulter dossier client
@enduml
