@startuml
title DA003 - Gestion des contacts

(*) --> "Lister les contacts du client" as listClient

listClient --> "Consulter un contact" as consulter
listClient --> "Créer un contact" as creer_contact

consulter --> "Modifier les données d'un contact" as modifier

@enduml
