@startuml
title DA3: Gérer les contacts\n


:Lister les contacts du client;
split
    :Consulter un contact;
    :Modifier les données d'un contact;
split again
    :Créer un contact;
end split

@enduml
