@startuml
title DSA003 - Gestion des contacts

actor Agent
participant Interface as IHM
participant "Services\nMétier\nApplicatifs" as SMA
participant Contact as C
participant Client
participant Structure
participant Contrat
participant Produit


Agent -> IHM : listerContactsClient(idClient)

'TODO...

@enduml
