@startuml

title DSS4.4: Choisir périodicité\n

actor Agent as A
participant IHM
participant Système


A -> IHM : Choisir périodicité
    IHM -> Système : listerContratsClient(**idClient**)
    Système --> IHM : liste<//Souscription//, //Domaine//>
    IHM -> Système : rechercherContrat(**codeSouscription**)
    Système --> IHM : //Souscription//, //Domaine//, liste<//Option//>
    IHM -> Système : previsualiserMensualites(**periodicite**, **codeSouscription**)
    Système --> IHM : //Mensualites//
    IHM -> Système : choisirPeriodicite(**periodicite**, **codeSouscription**)
    Système --> IHM : //Souscription//

@enduml