@startuml
title DA4: Consulter contrats client\n
split
:Rechercher contrat client;


	:Lister tous les contrats client;
	split
	:Choisir contrat;
	split again
	:Créer nouveau contrat client;
	end split

split again 
:Rechercher dernier contrat client;
end split
:Consulter contrat client;
	split
		:Details option;
	split again
		:Resilier option;
	split again
		:Souscrire option;
	split again
		:Choisir periodicite;
		:Valider periodicite;
	split again 
		:Résilier contrat;
	end split
@enduml