@startuml
title DA4.1: Gestion des contrats\n

:Rechercher Contrats Client;
:Choisir contrat;
:Consulter contrat;
split
:Details option;
split again
:Resilier option;
split again
:Souscrire option;
split again
:Choisir mensualite;
:Valider mensualite;
end split
@enduml
